### ISSUE TITLE
Error: Error #2030

### ISSUE THREAD

**Issue by march1993** [magicalhobo/SWFWire#53]
hi
https://www.dropbox.com/s/evp4e9v9sj12hi0/a.swf?dl=0
failed when parsing this swf file

and

does SWFWire support avm1 decompliling?
it seems that there's only code for DoABCTag in your src code.

**Comment by magicalhobo** [comment]
Thanks for the link. No, it doesn't support decompiling AS2. It would be a lot of work, and I think at this point it's not going to be done. Anyway, it shouldn't throw an error, so this is a bug.

**Comment by march1993** [comment]
okay. anyway your work is magnificent.
